Repository BAM-karaokebox/bkb-backoffice-tests, pull requests merged in 2022-04, with the labels that each got.

#1 BAM-986 Update playwright.yml
  .github/workflows/playwright.yml
Labels: echoes/intent: throughput, echoes/intent: risk-mitigation, echoes/effort: S

#2 Bam 986 test as a backend user i get a notification as soon as a price is wrong
  .github/workflows/playwright.yml
Labels: echoes/intent: risk-mitigation, echoes/effort: S

#3 Bam 986 test as a backend user i get a notification as soon as a price is wrong
  playwright.config.ts
  tests/testPrice.spec.ts
Labels: echoes/intent: risk-mitigation, echoes/effort: S

#4 BAM-1014 rule venues in paris report an error because the floor price is too high
  .editorconfig
  playwright.config.ts
  tests/testPrice.spec.ts
Labels: echoes/intent: throughput, echoes/intent: risk-mitigation, echoes/effort: XS

#5 Release 2022-04-29
  .editorconfig
  .github/workflows/playwright.yml
  playwright.config.ts
  tests/testPrice.spec.ts
Labels: echoes/intent: throughput, echoes/intent: risk-mitigation, echoes/effort: XS
